import {StyleSheet} from 'react-native';
import colors from "./colors";

export const Typography = StyleSheet.create({
    displayL: {
        fontSize: 57,
        fontWeight: '400',
        lineHeight: 64,
        letterSpacing: -.25,
        color: colors.black,
    },
    displayM: {
        fontSize: 45,
        fontWeight: '400',
        lineHeight: 52,
        letterSpacing: 0,
        color: colors.black,
    },
    displayS: {
        fontSize: 36,
        fontWeight: '400',
        lineHeight: 44,
        letterSpacing: 0,
        color: colors.black,
    },
    headingL: {
        fontSize: 32,
        fontWeight: '400',
        lineHeight: 40,
        letterSpacing: 0,
        color: colors.black,
    },
    headingM: {
        fontSize: 28,
        fontWeight: '400',
        lineHeight: 36,
        letterSpacing: 0,
        color: colors.black,
    },
    headingS: {
        fontSize: 24,
        fontWeight: '400',
        lineHeight: 32,
        letterSpacing: 0,
        color: colors.black,
    },
    titleL: {
        fontSize: 22,
        fontWeight: '400',
        lineHeight: 28,
        letterSpacing: 0,
        color: colors.black,
    },
    titleM: {
        fontSize: 16,
        fontWeight: '400',
        lineHeight: 24,
        letterSpacing: 0.15,
        color: colors.black,
    },
    titleS: {
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 20,
        letterSpacing: .1,
        color: colors.black,
    },
    bodyL: {
        fontSize: 16,
        fontWeight: '400',
        lineHeight: 24,
        letterSpacing: .5,
        color: colors.black,
    },
    bodyM: {
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 20,
        letterSpacing: .25,
        color: colors.black,
    },
    bodyS: {
        fontSize: 12,
        fontWeight: '400',
        lineHeight: 16,
        letterSpacing: .4,
        color: colors.black,
    },
    labelL: {
        fontSize: 14,
        fontWeight: '500',
        lineHeight: 20,
        letterSpacing: .1,
        color: colors.black,
    },
    labelM: {
        fontSize: 12,
        fontWeight: '500',
        lineHeight: 16,
        letterSpacing: .5,
        color: colors.black,
    },
    labelS: {
        fontSize: 11,
        fontWeight: '500',
        lineHeight: 16,
        letterSpacing: .5,
        color: colors.black,
    }
})